# Generated by Django 6.0.7 on 2026-08-10 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0006_alter_chapter_course_alter_chapter_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='handbook.course'),
        ),
    ]
